name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest
      
      - name: Install dependencies
        run: bun install
      
      - name: Lint
        run: bun run lint
      
      - name: Build
        run: bun run build
      
      - name: Test with coverage
        run: bun run test
        
      - name: Create combined coverage directory
        run: |
          mkdir -p coverage
          [ -f packages/core/coverage/lcov.info ] && cp packages/core/coverage/lcov.info coverage/lcov.core.info || echo "No coverage for core"
          [ -f packages/app/coverage/lcov.info ] && cp packages/app/coverage/lcov.info coverage/lcov.app.info || echo "No coverage for app"
          [ -f packages/core/coverage/lcov.info ] || [ -f packages/app/coverage/lcov.info ] && cat coverage/lcov.*.info > coverage/lcov.info || echo "No coverage files found"
          ls -la coverage || echo "Coverage directory empty or not found"

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          files: ./coverage/lcov.info
