name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest
      
      - name: Install dependencies
        run: bun install
      
      - name: Lint
        run: bun run lint
      
      - name: Build
        run: bun run build
      
      - name: Test with coverage
        run: bun run test

      - name: Merge coverage reports
        run: |
          mkdir -p coverage
          cp packages/core/coverage/coverage.lcov coverage/lcov.core.info 2>/dev/null || echo "no core coverage"
          cp packages/app/coverage/coverage.lcov coverage/lcov.app.info 2>/dev/null || echo "no app coverage"
          cat coverage/lcov.*.info > coverage/lcov.info
          ls -la coverage

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          files: coverage/lcov.info
